module Parsers
  class Parser
    attr_reader errors: untyped

    def initialize: (untyped lexer) -> void

    def parse_program: () -> Ast::Program

    private

    def next_token: () -> Tokens::Token

    def parse_let_statement: () -> (nil | Ast::LetStatement)

    def parse_statement: () -> (nil | Ast::Statement)

    def expect_peek?: (Tokens::TokenType token_type) -> bool

    def peek_token_is?: (Tokens::TokenType token_type) -> bool
  end
end
